automation: job chaining, qa report and pushresults

diff --git a/belfry b/belfry
--- a/belfry
+++ b/belfry
@@ -67,6 +67,31 @@ callpullrsync() {
 export -f callpullrsync
 
 
+callpullrsync_noshorah() {
+	. server.conf
+
+	arglist=( )
+	if (( ${#@} )); then
+		arglist=( "${@/#/bellfry@euler.ethz.ch::${working}/samples/}" )
+	else
+		arglist=( "bellfry@euler.ethz.ch::${working}/samples/" )
+	fi
+	exec rsync	--password-file ~/rsync.pass.euler	\
+		-e "ssh -i ${HOME}/.ssh/id_ed25519_bellfry -l ${USER%%@*}"	\
+		-izrltH --fuzzy --fuzzy --inplace	\
+		-p --chmod=Dg+s,ug+rw,o-rwx	\
+		-g --chown=:"${storgrp}"	\
+		--link-dest=${basedir}/${sampleset}/	\
+		"${arglist[@]}"	\
+		--exclude='raw_data/*_R[12].fastq.gz'	\
+		--exclude='extracted_data/R[12]_fastqc.html'	\
+		--exclude 'variants/'	\
+		--exclude 'visualization/'	\
+		${basedir}/${working}/samples/
+}
+export -f callpullrsync_noshorah
+
+
 case "$1" in
 	syncopenbis)
 		# Total: 10654 directories, 11687 files, 0 symlink
@@ -122,6 +147,21 @@ case "$1" in
 			--list-only	\
 			bellfry@euler.ethz.ch::${working}/samples/
 	;;
+	pullsamples_noshorah)
+		rsync	--password-file ~/rsync.pass.euler	\
+			-e "ssh -i ${HOME}/.ssh/id_ed25519_bellfry -l ${USER%%@*}"	\
+			-izrltH --fuzzy --fuzzy --inplace	\
+			-p --chmod=Dg+s,ug+rw,o-rwx	\
+			-g --chown=:"${storgrp}"	\
+			--relative	\
+			bellfry@euler.ethz.ch::${working}/./{qa.csv,variants/}	\
+			${basedir}/${working}/
+		echo "samples:"
+		cut -s --fields=1 ${basedir}/${sampleset}/samples.*.tsv|sort -u|	\
+			gawk -v P=$(( parallel * 4 )) '{i=(NR-1);b=i%P;o[b]=(o[b] " \"" $1 "\"")};END{for(i=0;i<P;i++){printf("%s\0",o[i])}}'|	\
+			xargs -0 -P $parallel -I '{@LIST@}' --	\
+				bash -c "callpullrsync_noshorah {@LIST@} " || echo "Error on some rsync jobs"
+	;;
 	pullsamples)
 		rsync	--password-file ~/rsync.pass.euler	\
 			-e "ssh -i ${HOME}/.ssh/id_ed25519_bellfry -l ${USER%%@*}"	\
@@ -136,5 +176,27 @@ case "$1" in
 			gawk -v P=$(( parallel * 4 )) '{i=(NR-1);b=i%P;o[b]=(o[b] " \"" $1 "\"")};END{for(i=0;i<P;i++){printf("%s\0",o[i])}}'|	\
 			xargs -0 -P $parallel -I '{@LIST@}' --	\
 				bash -c "callpullrsync {@LIST@} " || echo "Error on some rsync jobs"
+	;;
+	qa_report)
+		. $baseconda/miniconda3/bin/activate qa_report
+		cd ${basedir}/${working}/
+		jupyter nbconvert --execute --no-input qa_report.ipynb
+		conda deactivate
+	;;
+	pushseq)
+		# TODO a git repo
+		if [[ ${2} =~ ^(batch_[[:digit:]]+)$ ]]; then
+			pushdir="$(realpath "$basedir/../pangolin/consensus_data/${2}")"
+		else
+			echo "Bad push target ${2}"
+			exit 1
+		fi
+
+		rsync -irltH  --fuzzy --fuzzy --inplace	\
+			-p --chmod=Dg+s,ug+rw,o-rwx	\
+			-g --chown=:"${storgrp}"	\
+			--relative	\
+			${basedir}/${working}/./{qa*.html,qa*.csv,samples/{[[:digit:]]*_[[:digit:]]*_[[:upper:]][[:digit:]]*,[[:upper:]][[:digit:]]*_[[:digit:]]*}/[[:digit:]]*_*/references/}	\
+			${pushdir}
 	;;
 esac
