Autonomous download added for Health2030
 - unlike other sources, it's not always on mirror, but alternates between two states
 - state 1: light-weight list / wait for new folders
 - state 2: full mirror / until all md5 sums pass

diff --git a/belfry b/belfry
--- a/belfry
+++ b/belfry
@@ -31,6 +31,7 @@ baseconda=$HOME/
 timeoutforeground=
 #--foreground
 
+now=$(date '+%Y%m%d')
 lastmonth=$(date '+%Y%m' --date='-1 month')
 thismonth=$(date '+%Y%m')
 
@@ -46,10 +47,13 @@ validateBatchDate() {
 	fi
 }
 
+#
+# rsync parallel helpers
+#
 callpushrsync() {
 	. server.conf
 
-	arglist=( )
+	local arglist=( )
 	if (( ${#@} )); then
 		arglist=( "${@/#/${basedir}/${sampleset}/}" )
 	else
@@ -73,7 +77,7 @@ export -f callpushrsync
 callpullrsync() {
 	. server.conf
 
-	arglist=( )
+	local arglist=( )
 	if (( ${#@} )); then
 		arglist=( "${@/#/belfry@euler.ethz.ch::${working}/samples/}" )
 	else
@@ -103,7 +107,7 @@ export -f callpullrsync
 callpullrsync_noshorah() {
 	. server.conf
 
-	arglist=( )
+	local arglist=( )
 	if (( ${#@} )); then
 		arglist=( "${@/#/belfry@euler.ethz.ch::${working}/samples/}" )
 	else
@@ -129,6 +133,28 @@ callpullrsync_noshorah() {
 export -f callpullrsync_noshorah
 
 
+#
+# sync helper
+#
+checksyncoutput() {
+	local new="${statusdir}/sync${1}_new"
+	local last="${statusdir}/sync${1}_last"
+
+	if [[ "${2}" =~ Total:\ +([[:digit:]]+)\ +directories,\ +([[:digit:]]+)\ +files,.*?New:\ +([[:digit:]]+)\ +files, ]]; then
+		echo "Newfiles downloaded"
+		echo -e "${BASH_REMATCH[2]}\n${BASH_REMATCH[1]}" > ${last}
+		flock -x -o ${last} -c "sleep 1"
+		echo "${BASH_REMATCH[3]}" > ${new}
+	else
+		echo "Same old shit"
+		touch ${last}
+	fi 2>&1
+}
+
+
+#
+# main handler
+#
 case "$1" in
 	syncopenbis)
 		echo "Sync GFB - OpenBIS..."
@@ -143,15 +169,7 @@ case "$1" in
 			param=( )
 		fi
 		syncoutput="$(/usr/bin/time ${scriptdir}/sync_sftp -c gfb.conf "${param[@]}"|tee /dev/stderr)"
-		if [[ "$syncoutput" =~ Total:\ +([[:digit:]]+)\ +directories,\ +([[:digit:]]+)\ +files,.*?New:\ +([[:digit:]]+)\ +files, ]]; then
-			echo "Newfiles downloaded"
-			echo -e "${BASH_REMATCH[2]}\n${BASH_REMATCH[1]}" > ${statusdir}/syncopenbis_last
-			flock -x -o ${statusdir}/syncopenbis_last -c "sleep 1"
-			echo "${BASH_REMATCH[3]}" > ${statusdir}/syncopenbis_new
-		else
-			echo "Same old shit"
-			touch ${statusdir}/syncopenbis_last
-		fi 2>&1
+		checksyncoutput "openbis" "$syncoutput"
 		conda deactivate
 	;;
 	syncfgcz)
@@ -162,19 +180,40 @@ case "$1" in
 # # 			param=( "${lastmonth}*" "${thismonth}*" )
 # # 			echo "syncing recent: ${param[*]}"
 # 		else
-# 			param=( )
+			param=( 'p23224' 'p23212' )
 # 		fi
-		param=( 'p23224' 'p23212' )
 		syncoutput="$(/usr/bin/time ${scriptdir}/sync_sftp -c fgcz.conf "${param[@]}"|tee /dev/stderr)"
-		if [[ "$syncoutput" =~ Total:\ +([[:digit:]]+)\ +directories,\ +([[:digit:]]+)\ +files,.*?New:\ +([[:digit:]]+)\ +files, ]]; then
-			echo "Newfiles downloaded"
-			echo -e "${BASH_REMATCH[2]}\n${BASH_REMATCH[1]}" > ${statusdir}/syncopenbis_last
-			flock -x -o ${statusdir}/syncopenbis_last -c "sleep 1"
-			echo "${BASH_REMATCH[3]}" > ${statusdir}/syncfgcz_new
-		else
-			echo "Same old shit"
-			touch ${statusdir}/syncfgcz_last
-		fi 2>&1
+		checksyncoutput "fgcz" "$syncoutput"
+		conda deactivate
+	;;
+	synch2030)
+		echo "Sync Health2030"
+		. $baseconda/miniconda3/bin/activate ""
+		# short test - only list dirs
+		if [[ ( ( ! -e ${statusdir}/synch2030_ended ) && ( ! -e ${statusdir}/synch2030_started ) ) || ( ${statusdir}/synch2030_ended -nt ${statusdir}/synch2030_started ) ]]; then
+			${scriptdir}/list_sftp -c h2030.conf -l ${statusdir}/synch2030.${now}	&&	\
+			if [[ -s ${statusdir}/synch2030.${now} ]]; then
+				ln -sf synch2030.${now} ${statusdir}/synch2030_started
+			fi
+			# did we get new list?
+			if [[ ( -e ${statusdir}/synch2030_started ) && ( ( ! -e ${statusdir}/synch2030_ended ) || ( ${statusdir}/synch2030_started -nt ${statusdir}/synch2030_ended ) ) ]]; then
+				cat ${statusdir}/synch2030_started
+			else
+				echo "no new dirs"
+			fi
+		fi
+		# long sync - full mirror
+		if [[ ( -e ${statusdir}/synch2030_started ) && ( ( ! -e ${statusdir}/synch2030_ended ) || ( ${statusdir}/synch2030_started -nt ${statusdir}/synch2030_ended ) ) ]]; then
+			syncoutput="$(/usr/bin/time ${scriptdir}/sync_sftp -c h2030.conf |tee /dev/stderr)"
+			checksyncoutput "h2030" "$syncoutput"
+			${scriptdir}/check_sums -c h2030.conf 'md5.txt' $( < ${statusdir}/synch2030_started)
+			# 2: internal error, grep error
+			# 1: no failed checksum found
+			# 0: failed checksum found
+			if [[ "$?" == "1" ]]; then
+				touch ${statusdir}/synch2030_ended
+			fi
+		fi
 		conda deactivate
 	;;
 	sortsamples)
