adding push/pull functionality

diff --git a/belfry b/belfry
--- a/belfry
+++ b/belfry
@@ -18,6 +18,9 @@ declare -A lab
 : ${retries:=10}
 : ${iotimeout:=300}
 : ${protocolyaml:=/references/primers.yaml}
+: ${viloca_results:?}
+: ${viloca_remote_basedir:work-viloca}
+: ${viloca_remote_resultsdir:results}
 
 if [[ $(realpath $scriptdir) != $(realpath $basedir) ]]; then
 	echo "$scriptdir vs $basedir"
@@ -36,6 +39,8 @@ umask 0002
 
 statusdir="${basedir}/status"
 mkdir ${mode:+--mode=${mode}} -p ${statusdir}
+viloca_statusdir="${basedir}/${viloca_basedir}/status"
+mkdir ${mode:+--mode=${mode}} -p ${viloca_statusdir}
 
 baseconda=$HOME/
 timeoutforeground=
@@ -159,6 +164,28 @@ callpullrsync_noshorah() {
 }
 export -f callpullrsync_noshorah
 
+callpullrsync_viloca() {
+	. server.conf
+
+	local arglist=( )
+	if (( ${#@} )); then
+		arglist=( "${@/#/belfry@euler.ethz.ch::${working}/samples/}" )
+	else
+		#arglist=( "belfry@euler.ethz.ch::${working}/samples/" )
+		echo "rsync job didn't receive list"
+		exit 1;
+	fi
+	exec	timeout ${timeoutforeground} --signal=INT --kill-after=5 $((rsynctimeout+contimeout+5))	\
+		rsync	--timeout=${iotimeout}	\
+		--password-file ~/rsync.pass.euler	\
+		-e "ssh -i ${HOME}/.ssh/id_ed25519_belfry -l ${cluster_user}  -oConnectTimeout=${contimeout}"	\
+		-izrltH --fuzzy --fuzzy --inplace	\
+		--link-dest=${viloca_remote_basedir}/${viloca_remote_results}/	\
+		"${arglist[@]}"	\
+		--exclude='alignment/'	\
+		${viloca_results}/
+}
+export -f callpullrsync_viloca
 
 #
 # sync helper
@@ -403,6 +430,24 @@ case "$1" in
 			touch ${statusdir}/pushsampleset_success
 		fi
 	;;
+	pushvilocasamplelist)
+		err=0
+		timeout ${timeoutforeground} --signal=INT --kill-after=5 $((rsynctimeout+contimeout+5))	\
+			rsync	--timeout=${iotimeout}	\
+			--password-file ~/rsync.pass.euler	\
+			-e "ssh -i ${HOME}/.ssh/id_ed25519_belfry -l ${cluster_user}  -oConnectTimeout=${contimeout}"	\
+			-izrltH --fuzzy --fuzzy --inplace	\
+			-p --chmod=Dg+s,ug+rw,o-rwx,Fa-x	\
+			-g --chown=:'bsse-covid19-pangolin-euler'	\
+			${viloca_basedir}/samples.csv	\
+			belfry@euler.ethz.ch::${viloca_remote_basedir}/ || (( ++err ))
+		if (( err )); then
+			echo "Error: ${err} rsync job(s) failed"
+			touch ${statusdir}/pushsamplelist_viloca_fail
+		else
+			touch ${statusdir}/pushsamplelist_viloca_success
+		fi
+	;;
 	listsamples)
 		timeout ${timeoutforeground} --signal=INT --kill-after=5 $((rsynctimeout+contimeout+5))	\
 			rsync	--timeout=${iotimeout}	\
@@ -573,6 +618,48 @@ case "$1" in
 			rmdir "${f%/}"
 		done
 		mv "${sampleset}/batch.${2}.yaml" "${sampleset}/samples.${2}.tsv" "${sampleset}/missing.${2}.txt" "${sampleset}/projects.${2}.tsv" garbage/
+	;;
+	pullsamples_viloca)
+		# fetch remote sheets
+		mkdir -p /tmp/belfrysheets/
+		if [[ "${2}" = "--batch" ]]; then
+			validateBatchName "${3}"
+			sheets=( "belfry@euler.ethz.ch::${sampleset}/samples.${3}.tsv"  )
+		elif [[ "${2}" = "--catchup" ]]; then
+			sheets=( "belfry@euler.ethz.ch::catchup/samples.catchup.tsv"  )
+		else
+			sheets=( "belfry@euler.ethz.ch::${sampleset}/samples.2*.tsv" )
+		fi
+		rsync	\
+			--password-file ~/rsync.pass.euler	\
+			-e "ssh -i ${HOME}/.ssh/id_ed25519_belfry -l ${cluster_user} "	\
+			-izrltH --fuzzy --fuzzy --inplace	\
+			-p --chmod=Dg+s,ug+rw,o-rwx	\
+			-g --chown=:"${storgrp}"	\
+			"${sheets[@]}"	\
+			/tmp/belfrysheets/
+		if [[ "${2}" = "--batch" ]]; then
+			validateBatchName "${3}"
+			sheets=( "/tmp/belfrysheets/samples.${3}.tsv"  )
+		elif [[ "${2}" = "--catchup" ]]; then
+			sheets=( "/tmp/belfrysheets/samples.catchup.tsv"  )
+		else
+			sheets=( /tmp/belfrysheets/samples.2*.tsv )
+		fi
+		err=0
+		echo "samples:"
+		cut -s --fields=1 "${sheets[@]}"|sort -u|	\
+			gawk -v P=$(( parallelpull * 4 )) '{i=(NR-1);b=i%P;o[b]=(o[b] " \"" $1 "\"")};END{for(i=0;i<P;i++){printf("%s\0",o[i])}}'|	\
+			xargs -0 -P $parallelpull -I '{@LIST@}' --	\
+				bash -c "callpullrsync_viloca {@LIST@} " || (( ++err ))
+		if (( err )); then
+			echo "Error: ${err} rsync job(s) failed"
+			touch ${viloca_statusdir}/pullsamples_viloca_fail
+		elif [[ "${2}" = "--catchup" ]]; then
+			echo -e '\n\e[38;5;45;1mFor the good of all of us\e[0m\n\e[38;5;208;1mExcept the ones who are dead\e[0m'
+		else
+			touch ${viloca_statusdir}/pullsamples_viloca_success
+		fi
 	;;
 	*)
 		echo "Unkown sub-command ${1}" > /dev/stderr
