Patch remap: force a specific TSV
 - for batches that combine multiple projects/orders

diff --git a/patch_rename b/patch_rename
--- a/patch_rename
+++ b/patch_rename
@@ -56,13 +56,18 @@ lab="${BASH_REMATCH[1]}"
 case "$lab" in
 	fgcz)
 		echo "patch remapping for fgcz"
-		[[ "${batch}" =~ order:[[:space:]]+o?([[:digit:]]+) ]] || fail "Cannot find order" $'file was:\n'"${batch}"
-		order="${BASH_REMATCH[1]}"
-		echo "order ${order}"
-		[[ "${batch}" =~ project:[[:space:]]+p?([[:digit:]]+) ]] || fail "Cannot find project" $'file was:\n'"${batch}"
-		project="${BASH_REMATCH[1]}"
-		echo "project ${project}"
-		patchfile="${sampleset}/patch.${project}.${order}.tsv"
+		if [[ "${2}" == "--force" ]]; then
+			patchfile="${3}"
+			echo "forcing patchfile ${patchfile}"
+		else
+			[[ "${batch}" =~ order:[[:space:]]+o?([[:digit:]]+) ]] || fail "Cannot find order" $'file was:\n'"${batch}"
+			order="${BASH_REMATCH[1]}"
+			echo "order ${order}"
+			[[ "${batch}" =~ project:[[:space:]]+p?([[:digit:]]+) ]] || fail "Cannot find project" $'file was:\n'"${batch}"
+			project="${BASH_REMATCH[1]}"
+			echo "project ${project}"
+			patchfile="${sampleset}/patch.${project}.${order}.tsv"
+		fi
 	;;
 	*)
 		fail "Unknown lab $lab"
@@ -106,7 +111,7 @@ while read old new trash; do
 
 	sed -si "1s/${longold}/${longnew}/g" "${working}/samples/${new}/${batchname}/alignments/REF_aln_stats.yaml" "${working}/samples/${new}/${batchname}/references/"*.fasta
 	sed -i "s@${old}([-/])${batchname}@${new}\{1}${batchname}@g;s/^${longold:0:6}/${longnew:0:6}/g" "${working}/samples/${new}/${batchname}/references/"*.matcher
-	sed -i "s/${longold}/${longnew}/g" "${working}/samples/${new}/${batchname}/references/frameshift_deletions_check.csv"
+	sed -i "s/${longold}/${longnew}/g" "${working}/samples/${new}/${batchname}/references/frameshift_deletions_check.tsv"
 
 	touch --reference="${working}/samples/${old}" "${working}/samples/${new}"
 	rmdir "${working}/samples/${old}"
