Protocols in mass-importers for Viollier and FGCZ

diff --git a/sort_viollier b/sort_viollier
--- a/sort_viollier
+++ b/sort_viollier
@@ -2,9 +2,11 @@
 
 configfile=server.conf
 
-usage() { echo "Usage: $0 [-c <configfile>] [-r <recent>] [ <directories [...]> ]" 1>&2; exit $1; }
+usage() { echo "Usage: $0 [-c <configfile>] [-r <recent>] [ -4 <protocolsyaml> ] [ <directories [...]> ]" 1>&2; exit $1; }
 
-while getopts "c:r:h" o; do
+protocolsyaml=
+
+while getopts "c:r:4:h" o; do
 	case "${o}" in
 		c)	configfile=${OPTARG}
 			if [[ ! -r ${configfile} ]]; then
@@ -15,6 +17,12 @@ while getopts "c:r:h" o; do
 		r)	recent=${OPTARG}
 			if [[ ! ${recent} =~ ^20[[:digit:]]{2}([01][[:digit:]]([0-3][[:digit:]])?)?$ ]]; then
 				echo "Wrong format ${recent}" 1>&2
+				usage 2
+			fi
+			;;
+		4)	protocolsyaml=${OPTARG}
+			if [[ ! -r ${protocolsyaml} ]]; then
+				echo "Cannot read ${protocolsyaml}" 1>&2
 				usage 2
 			fi
 			;;
@@ -117,7 +125,7 @@ SH_BAR
 			echo "Patchmap found for $(basename ${d})"
 			patchmap="--patchmap=${d%%/}.patchmap.tsv"
 		fi
-		./sort_samples_jobinfo --summary --sourcedir=${d} ${patchmap} --outdir=${basedir}/${sampleset} ${mode:+--mode=${mode}} --force --forcelanes --batch ${lab} --append --staging
+		./sort_samples_jobinfo --summary --sourcedir=${d} ${patchmap} --outdir=${basedir}/${sampleset} ${mode:+--mode=${mode}} --force --forcelanes --batch ${lab} --append --staging ${protocolsyaml:+--protocols=${protocolsyaml}}
 		# between appended batches: combine error status into overall status  & reset local error status
 		cat >> ${basedir}/${sampleset}/movedatafiles.sh <<MERGE_ALLOK
 (( GRANDTOTAL_ALLOK &= ALLOK ))
