Fix-up env & typos
 - typo and missing lines in handle_request_raw_viollier and upload_viollier_raw
 - shebang for python
 - vineyard conda environment

diff --git a/upload_viollier_raw b/upload_viollier_raw
--- a/upload_viollier_raw
+++ b/upload_viollier_raw
@@ -62,6 +62,10 @@ while read aufxx ethid rest; do
 	# skip empty lines
 	if [[ -z ${auf} ]]; then
 		continue
+	elif [[ ! ${auf} =~ ^[[:digit:]]{8,} ]]; then
+		echo "cannot parse ${auf}" >&2
+		error=1
+		continue
 	fi
 	aufnum=${BASH_REMATCH[0]}
 
